ARG FEDORA_VERSION=36

FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION}

RUN dnf install -y \
    "@Development Tools" \
	pandoc \
    openssl \
    openssl1.1-devel.x86_64 \
    java \
    python \
    pip \
    pipx \
    sshpass
