ARG FEDORA_VERSION=36

FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION}

RUN dnf install -y \
    "@Development Tools" \
    pandoc \
    openssl \
    openssl1.1-devel.x86_64 \
    java \
    python \
    pip \
    pipx \
    sshpass \
    android-tools

# Add the custom repo for VSCode and install it
# https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
COPY repos/vscode.repo /etc/yum.repos.d/
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc \
    && dnf check-update || true \
    && dnf install -y code
