---
- name: Ensure that vim and neovim are installed
  become: yes
  apt:
      state: present
      name:
        - vim
        - neovim

# ---------------------------------------------------------------------
# vim config

- name: Ensure that custom .vimrc is in the home folder
  copy:
      src: .vimrc
      dest: "{{ lookup('env', 'HOME') }}/.vimrc"

# ---------------------------------------------------------------------
# vim-plug (for managing vim plugins)

- name: Ensure that the .vim/autoload folder exists
  file:
      path: "{{ lookup('env', 'HOME') }}/.vim/autoload"
      state: directory

# ---------------------------------------------------------------------
# neovim config

- name: Ensure that the nvim config folder exists
  file:
      path: "{{ lookup('env', 'HOME') }}/.config/nvim"
      state: directory

- name: Ensure that custom neovim init file is in nvim config folder
  copy:
      src: init.vim
      dest: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"