---

- name: Ensure that the nix config directory exists
  ansible.builtin.file:
      path: "{{ nixconfig }}"
      state: directory

- name: Ensure that custom nix.conf is in the nix config folder
  ansible.builtin.copy:
      src: nix.conf
      dest: "{{ nixconfig }}/nix.conf"

