---

- name: Ensure that all startpage files are in the startpage folder
  ansible.posix.synchronize:
    src: Homepage
    dest: "{{ browser_startpage_folder }}"

- name: Ensure that the browser policy directories exist
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: "{{ policy_folder }}"
    state: directory
    owner: root
    group: root
    mode: u=rw,go-rwx
  loop: "{{ browser_policy_folders | default([]) }}"
  loop_control:
    loop_var: policy_folder

- name: Ensure that browser policy is present in the policy folders
  become: yes
  become_method: sudo
  ansible.builtin.template:
    src: templates/custom_policy.json.jinja2
    dest: "{{ policy_folder }}/custom_policy.json"
    owner: root
    group: root
    mode: u=r,go-rwx
  loop: "{{ browser_policy_folders | default([]) }}"
  loop_control:
    loop_var: policy_folder