# https://chromeenterprise.google/policies/#WebAppInstallForceList
#
# if we have chosen to install the 'com.brave.Browser', the playbook
# will also include the below policy

# the keys in the below list are all directly taken from the schema
# of the WebAppInstallForceList chrome policy.

chromium_web_apps:
  - url: https://app.fastmail.com/mail/
    create_desktop_shortcut: true
    default_launch_container: window
  - url: https://github.com/
    create_desktop_shortcut: true
    default_launch_container: window
  - url: https://old.reddit.com/
    create_desktop_shortcut: true
    default_launch_container: window
  - url: https://www.youtube.com/
    create_desktop_shortcut: true
    default_launch_container: window

# https://chromeenterprise.google/policies/#ExtensionInstallForcelist
#
# the keys in this list are taking from the extension force install
# list
#
# you can optionally provide a semi-colon separated "update" URL which
# points to an Update Manifest XML document (for self-hosted Chrome
# extensions), but by default, the Chrome Web Store's update URL is used
#
# you can get the ID of an extension by installing it manually, and
# visiting 'chrome://extensions' (and enabling developer mode)

chromium_extensions:
  - "immpkjjlgappgfkkfieppnmlhakdmaab"  # Imagus

# other stuff (not ideal for management because the settings are
# reset each time the browser is updated... due to the way that
# Flatpak works)
# - "kbmfpngjjgdllneeigpgjifpgocmfgmb"  # Reddit Enhancement Suite
# - "dhdgffkkebhmkfjojejmpbldmpobfkfo"  # Tampermonkey
# - "fhcgjolkccmbidfldomjliifgaodjagh"  # Cookie AutoDelete
# - "mnjggcdmjocbbbhaepdhchncahnbgone"  # SponsorBlock for YouTube