---

- name: Ensuring that the required layered packages are present
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
    state: present
  become: yes
  become_method: sudo
  loop: "{{ packages_to_layer | default([]) }}"

- name: Ensuring that unnecessary layered packages are removed
  ansible.builtin.command: rpm-ostree override remove {{ item }}
  become: yes
  become_method: sudo
  loop: "{{ packages_to_remove | default([]) }}"

- debug:
    msg: "Reboot your machine to complete the package layering changes"
