#!/usr/bin/env bash

set -e

if command -v apt-get &> /dev/null
then
    sudo apt-get update
    sudo apt-get upgrade --assume-yes --autoremove
    sudo apt-get dist-upgrade --assume-yes
fi

if command -v flatpak &> /dev/null
then
    flatpak uninstall --assumeyes --unused
    flatpak update --assumeyes
fi
