#!/usr/bin/env bash

set -e

if command -v apt-get &> /dev/null
then
    sudo apt-get update
    sudo apt-get upgrade --autoremove
    sudo apt-get dist-upgrade
fi

if command -v flatpak &> /dev/null
then
    flatpak update
fi

if command -v snap &> /dev/null
then
    sudo snap refresh
fi
