---

- name: Ensure that all required Flatpak remotes are present
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    method: user
    flatpakrepo_url: "{{ item.url }}"
  loop: "{{ flatpak_remotes }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure that all unwanted Flatpak apps are absent
  community.general.flatpak:
    remote: "{{ item.remote }}"
    name: "{{ item.package }}"
    state: absent
  loop: "{{ flatpak_apps_to_remove }}"
  loop_control:
    label: "{{ item.package }}"

- name: Ensure that all required Flatpak apps are present
  community.general.flatpak:
    remote: "{{ item.remote }}"
    name: "{{ item.package }}"
    state: present
    method: user
  loop: "{{ flatpak_apps_to_install }}"
  loop_control:
    label: "{{ item.package }}"

# Flatpak overrides

- name: Ensure that Flatpak overrides are set up
  include_tasks: overrides.yml
  loop: "{{ flatpak_apps_to_install }}"
  loop_control:
    loop_var: flatpak
    label: "{{ flatpak.package }}"