---

# ---------------------------------------------------------------------
# install yt-dlp

# registering some facts first (to see if we need to do anything)

- name: Get the current stat of the yt-dlp binary
  ansible.builtin.stat:
      path: "{{ local_bin }}/yt-dlp"
  register: ytdlp_binary

- name: Get the current stat of the yt-dlp config file
  ansible.builtin.stat:
      path: "{{ local_bin }}/yt-dlp.conf"
  register: ytdlp_conf

# if necessary, download and install yt-dlp

- name: Download yt-dlp v2022.02.04
  ansible.builtin.get_url:
      url: https://github.com/yt-dlp/yt-dlp/releases/download/2022.02.04/yt-dlp
      dest: "{{ local_bin }}/yt-dlp"
      checksum: "sha256:a16fe3b3bd474d562c4b8645579b209377b967d58d4edffe6e31dc8de81d7283"
  when: >
    ytdlp_binary.stat.exists == false

- name: Ensure that the yt-dlp.conf file exists in the local bin
  ansible.builtin.copy:
      src: yt-dlp.conf
      dest: "{{ local_bin }}/yt-dlp.conf"

# set the correct file permissions

- name: Ensure that the yt-dlp binary can be executed by current user
  ansible.builtin.file:
      path: "{{ local_bin }}/yt-dlp"
      mode: u=rwx,go-rwx

- name: Ensure that the yt-dlp.conf is only readable by the current user
  ansible.builtin.file:
      path: "{{ local_bin }}/yt-dlp.conf"
      mode: u=r,go-rwx
