---

- name: Install custom RPM repos
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: u=rw,go=r
  with_fileglob:
    - "*.repo"

- name: Ensure that the required layered packages are present
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
    state: present
  become: yes
  become_method: sudo
  loop: "{{ packages_to_layer }}"

- name: Ensure that unnecessary layered packages are removed
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
    state: absent
  become: yes
  become_method: sudo
  loop: "{{ packages_to_remove }}"

- debug:
    msg: "Reboot your machine to complete the package layering changes"
