---
- name: Ensure that common packages are installed
  become: yes
  apt:
      state: present
      name:
        # all of the useful terminal commands
        # should be pre-installed but it's here just to make sure
        - coreutils

        # password manager
        # can also integrate with SSH agent
        - keepassxc

        # so that we can use `add-apt-repository`
        - software-properties-common
        - dirmngr
        - apt-transport-https
        - lsb-release
        - ca-certificates

        # other stuff
        - curl
        - fzf

# ---------------------------------------------------------------------
# create a folder to put my dotfiles and scripts

- name: Ensure that the .config/dotfiles directory exists
  file:
      path: "{{ lookup('env', 'HOME') }}/.config/dotfiles"
      state: directory

- name: Ensure that the .config/dotfiles/scripts directory exists
  file:
      path: "{{ lookup('env', 'HOME') }}/.config/dotfiles/scripts"
      state: directory